const mutations = {
  IS_LOGGED_IN: 'IS_LOGGED_IN',
  LOGIN_LOADER: 'LOGIN_LOADER',
  IS_CREATED: 'IS_CREATED',
  CREATING_LOADER: 'CREATING_LOADER',
  SHOW_NOTIFY: 'SHOW_NOTIFY',
  USER: 'USER',
  SENDING_LOADER: 'SENDING_LOADER',
};

export default mutations;
